const compromissos = [
  {
    _id: 7854,
    local: 'Santa Casa de Misericórdia de Maceió',
    assunto: 'Requerimento de Baixa Complexidade',
    horario: '2017-04-20 15:00:00.000Z',
    responsavel: 'James Ford',
    imgResponsavel: 'https://s-media-cache-ak0.pinimg.com/originals/14/3d/6b/143d6bfea7d2ecbfc61a0467f2f6261d.jpg',
    comparecido: false,
    extraInfo: {
      id: '7854',
      processo: '[15054] - 0801546-49.2014.4.05.8000',
      objeto: 'Confirmar a informação da Autora acerca da substituição do fármaco utilizado no seu tratamento de saúde juntando Relatório Médico para tanto.',
      'parte contrária': 'Quitéria Maria da Conceição de Lima',
      'instância atual': '13ª Vara Federal de Alagoas',
      'tipo intimidação': 'Correspondência',
      'data intimidação': '22/06/2015',
    },
  },
  {
    _id: 7855,
    local: 'Atlântica Serviços e Transportes LTDA.',
    assunto: 'Petição Inicial',
    horario: '2017-04-20 16:15:00.000Z',
    responsavel: 'John Locke',
    imgResponsavel: 'https://ewedit.files.wordpress.com/2015/01/lost-john-locke.jpg?w=612',
    comparecido: false,
    extraInfo: {
      id: '7854',
      processo: '[15054] - 0801546-49.2014.4.05.8000',
      objeto: 'Confirmar a informação da Autora acerca da substituição do fármaco utilizado no seu tratamento de saúde juntando Relatório Médico para tanto.',
      'parte contrária': 'Quitéria Maria da Conceição de Lima',
      'instância atual': '13ª Vara Federal de Alagoas',
      'tipo intimidação': 'Correspondência',
      'data intimidação': '22/06/2015',
    },
  },
  {
    _id: 7856,
    local: 'VSA EMPREENDIMENTO IMOBILIÁRIO SPE LTDA.',
    assunto: 'Defesa Administrativa',
    horario: '2017-04-20 17:00:00.000Z',
    responsavel: 'Jack Shepard',
    imgResponsavel: 'http://images2.fanpop.com/image/photos/9400000/jack-shephard-lost-9436809-550-733.jpg',
    comparecido: true,
    extraInfo: {
      id: '7854',
      processo: '[15054] - 0801546-49.2014.4.05.8000',
      objeto: 'Confirmar a informação da Autora acerca da substituição do fármaco utilizado no seu tratamento de saúde juntando Relatório Médico para tanto.',
      'parte contrária': 'Quitéria Maria da Conceição de Lima',
      'instância atual': '13ª Vara Federal de Alagoas',
      'tipo intimidação': 'Correspondência',
      'data intimidação': '22/06/2015',
    },
  },
  {
    _id: 7857,
    local: 'Santa Casa de Misericórdia de Maceió',
    assunto: 'Requerimento de Baixa Complexidade',
    horario: '2017-04-20 20:00:00.000Z',
    responsavel: 'James Ford',
    imgResponsavel: 'https://s-media-cache-ak0.pinimg.com/originals/14/3d/6b/143d6bfea7d2ecbfc61a0467f2f6261d.jpg',
    comparecido: false,
    extraInfo: {
      id: '7854',
      processo: '[15054] - 0801546-49.2014.4.05.8000',
      objeto: 'Confirmar a informação da Autora acerca da substituição do fármaco utilizado no seu tratamento de saúde juntando Relatório Médico para tanto.',
      'parte contrária': 'Quitéria Maria da Conceição de Lima',
      'instância atual': '13ª Vara Federal de Alagoas',
      'tipo intimidação': 'Correspondência',
      'data intimidação': '22/06/2015',
    },
  },
];

export default compromissos;
