const compromissos = [
  {
    _id: 7854,
    local: 'Santa Casa de Misericórdia de Maceió',
    assunto: 'Requerimento de Baixa Complexidade',
    horario: '2017-04-20 15:00:00.000Z',
    usuario: '001',
    check: false,
    editar: false,
    remover: false,
    extraInfo: {
      id: '7854',
      processo: '[15054] - 0801546-49.2014.4.05.8000',
      objeto: 'Confirmar a informação da Autora acerca da substituição do fármaco utilizado no seu tratamento de saúde juntando Relatório Médico para tanto.',
      'parte contrária': 'Quitéria Maria da Conceição de Lima',
      'instância atual': '13ª Vara Federal de Alagoas',
      'tipo intimidação': 'Correspondência',
      'data intimidação': '22/06/2015',
    },
  },
  {
    _id: 7855,
    local: 'Atlântica Serviços e Transportes LTDA.',
    assunto: 'Petição Inicial',
    horario: '2017-04-20 16:15:00.000Z',
    usuario: '002',
    check: true,
    editar: true,
    remover: true,
    extraInfo: {
      id: '7854',
      processo: '[15054] - 0801546-49.2014.4.05.8000',
      objeto: 'Confirmar a informação da Autora acerca da substituição do fármaco utilizado no seu tratamento de saúde juntando Relatório Médico para tanto.',
      'parte contrária': 'Quitéria Maria da Conceição de Lima',
      'instância atual': '13ª Vara Federal de Alagoas',
      'tipo intimidação': 'Correspondência',
      'data intimidação': '22/06/2015',
    },
  },
  {
    _id: 7856,
    local: 'VSA EMPREENDIMENTO IMOBILIÁRIO SPE LTDA.',
    assunto: 'Defesa Administrativa',
    horario: '2017-04-20 17:00:00.000Z',
    usuario: '003',
    check: false,
    editar: true,
    remover: true,
    extraInfo: {
      id: '7854',
      processo: '[15054] - 0801546-49.2014.4.05.8000',
      objeto: 'Confirmar a informação da Autora acerca da substituição do fármaco utilizado no seu tratamento de saúde juntando Relatório Médico para tanto.',
      'parte contrária': 'Quitéria Maria da Conceição de Lima',
      'instância atual': '13ª Vara Federal de Alagoas',
      'tipo intimidação': 'Correspondência',
      'data intimidação': '22/06/2015',
    },
  },
  {
    _id: 7857,
    local: 'Santa Casa de Misericórdia de Maceió',
    assunto: 'Requerimento de Baixa Complexidade',
    horario: '2017-04-20 20:00:00.000Z',
    usuario: '001',
    check: true,
    editar: true,
    remover: true,
    extraInfo: {
      id: '7854',
      processo: '[15054] - 0801546-49.2014.4.05.8000',
      objeto: 'Confirmar a informação da Autora acerca da substituição do fármaco utilizado no seu tratamento de saúde juntando Relatório Médico para tanto.',
      'parte contrária': 'Quitéria Maria da Conceição de Lima',
      'instância atual': '13ª Vara Federal de Alagoas',
      'tipo intimidação': 'Correspondência',
      'data intimidação': '22/06/2015',
    },
  },
];

export default compromissos;
